### ISSUE TITLE
Collapse / merge duplicates in graphs

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-app#32]
Multiple entries for `wa_i_15_2` carry the same chronological information, the same is true for `fischer-lamberg1955`. Maybe collapse or merge these graphs to make the viz easier to read.

**Comment by thvitt** [comment]
Is that issue still relevant?

**Comment by gerritbruening** [comment]
Don't know wether this is still relevant, as I don't remember to which it once referred.
