### ISSUE TITLE
Update schema

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-app#33]
1. update https://github.com/faustedition/faust-app/blob/master/faust-schema/src/main/odd/faust-tei.xml
2. inform MW when completed
3. run https://github.com/faustedition/faust-app/blob/master/faust-schema/pom.xml

**Comment by gerritbruening** [comment]
> Ich habe jetzt mal die wenigen Änderungen, die ich am bisherigen Faust-Schema vorgenommen hatte, im rng gepusht:
https://github.com/faustedition/faust-app/commit/c6b482667168c7cd2fff004f47e9ea8d26d3f576
Entsprechend geändert werden müsste aber das rnc-Schema.

@thvitt, könntest Du das übernehmen?

**Comment by thvitt** [comment]
Ich dachte, das ODD sei kanonisch, nicht das RNG?

**Comment by gerritbruening** [comment]
Sorry, ja, so steht es ja auch oben.
Und die erwähnten Änderungen sind auch schon drin:
https://github.com/faustedition/faust-app/blob/master/faust-schema/faust-tei.rng#L10344

**Comment by gerritbruening** [comment]
Dann müsste jetzt der [oben genannte](https://github.com/faustedition/faust-app/issues/33#issue-177451217) Schritt drei geschehen.

**Comment by thvitt** [comment]
There are even more schema files in the data (xml/schema). Need to check what is used, ideally we'd have a workflow for everything

**Comment by thvitt** [comment]
see https://github.com/faustedition/faust-schema
